// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM6gW07mG4_a0TGbDyonV0JMwxfHDmiHI',
    appId: '1:566561778940:android:b859e93394d681eecffb79',
    messagingSenderId: '566561778940',
    projectId: 'excurive-project',
    databaseURL: 'https://excurive-project.firebaseio.com',
    storageBucket: 'excurive-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZHLJDwS-Akw7CAgv1bcWy7sfmr8So34A',
    appId: '1:566561778940:ios:d793d784a190bafdcffb79',
    messagingSenderId: '566561778940',
    projectId: 'excurive-project',
    databaseURL: 'https://excurive-project.firebaseio.com',
    storageBucket: 'excurive-project.firebasestorage.app',
    androidClientId:
        '566561778940-t86767m72an2tsfpbb271c4qdela4jik.apps.googleusercontent.com',
    iosClientId:
        '566561778940-qov8fsmq95d6acuj1211p2o5ivmeepf9.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
